---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create and Deploy Public and Private Subnets'

Resources:
  VPC:
    Type: ''
    Properties:
      CidrBlock:
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Lab VPC
